### ISSUE TITLE
DNS Resolution

### ISSUE THREAD

**Issue by egreenspan2** [plixer/scrutinizer-datasource#2]
We need an option to return resolved host names in the report:

    "ipDns": {
        "selected": "dns"
    },

I attempted to add that tag to the reportData.js, but clearly I am missing the piece where the "label" should be use for data.
![image](https://user-images.githubusercontent.com/13028143/66720204-50b3ae00-edbf-11e9-9795-ae88b3402998.png)

Any thoughts on adding that as an option for the report?

**Comment by briandav22** [comment]
I did some looking into this. The problem is that the JSON data returned by the initial query doesn't contain the DNS information. Scrutinizer does these resolutions in the front end, once the initial data from the request is returned. 

![resolve](https://user-images.githubusercontent.com/32676990/67013267-d33eb500-f0c0-11e9-91f8-8c7771e82c46.png)

So my initial thought it

1.) Provide a drop down box to toggle (DNS/None DNS), only on reports that have IP Addresses in them. 
2.) Add a method around line 104 of datasource.js to intercept the returned JSON from scrutinizer, gather the IP addresses, convert them , then pass the converted data into the datahandler. 

![image](https://user-images.githubusercontent.com/32676990/67013970-02a1f180-f0c2-11e9-88a6-1b8ff8e47c08.png)

I'm going to think about this some more, I just wanted to give you some feedback on your attempt.

**Comment by briandav22** [comment]
This feature came up a couple more times, i was able to get some time to implement it. Made some progress adding in the DNS resolve checkbox, and returning the correct data. 

Only problem is it doesn't "hot swap" the IP / DNS resolution. Checking or Unchecking the 'Resolve DNS' box requires a full report reload. I'm not seeing a easy way around this. Going to play around with it a bit more before merging this feature branch into the master branch. 

![image](https://user-images.githubusercontent.com/32676990/74177595-0ecd3400-4c08-11ea-9e13-218e0d7bf2ec.png)

**Comment by jimmydnet** [comment]
+1 for this option. It would be cool if you could push both resolved/unresolved data the client as an array and then allow for the change to happen on the client end but I'm not sure how Grafana deals with this. Great work briandav22!

**Comment by briandav22** [comment]
this feature has been implemented along with the ability to hide others from the graph. 

![image](https://user-images.githubusercontent.com/32676990/74685468-a993b880-519c-11ea-99aa-e769018568f3.png)
