### ISSUE TITLE
Show Others Filter Request

### ISSUE THREAD

**Issue by brointhemix** [plixer/scrutinizer-datasource#5]
Hi,

Thanks for the great plugin!

I would like to request the possibility to turn on or off the Show Others graph on a per visualisation basis, so that I can create graphs where some show top N + others an some only show top N without others. Could that be done?

Thanks!

**Comment by 2rc** [comment]
What a great idea! :-)

**Comment by briandav22** [comment]
Starting work on this feature. It looks like in the query method we can intercept the data coming back from datahandler.formatData and filter out other traffic quite simply. 

![image](https://user-images.githubusercontent.com/32676990/74657811-007a9d00-515f-11ea-88f0-00e95d7422cb.png)

This yields a graph without other traffic. 

![image](https://user-images.githubusercontent.com/32676990/74657846-12f4d680-515f-11ea-9846-e5f943c5eb3b.png)

I'm going to experiment with ways to 'hot swap' the data via a checkbox instead of having to go to Scrutinizer and request the data again in order to display it without other traffic.

**Comment by brointhemix** [comment]
Thank you Brian! The chceckbox is exactly what we need :).

**Comment by briandav22** [comment]
have this wired to work with a button now. 

Currently this does require re-fetching the data and trimming out the 'other' traffic. Not a huge issue, but I'm going to play around with ways to swap data ad-hoc in the UI. This will help with the 'resolve dns' feature as well. 

If I can't get grafana to play nice , i'll push it to the master branch as is.

![image](https://user-images.githubusercontent.com/32676990/74668095-818f5f80-5172-11ea-8b90-2d047e61e960.png)

**Comment by briandav22** [comment]
Might switch to using sliders instead. I'm finding it easier to persist state this way. 

This matters mostly when you are saving the gadget to the dashboard then coming back to edit it later. 

![image](https://user-images.githubusercontent.com/32676990/74683975-80712900-5198-11ea-9854-413b211a45e9.png)

**Comment by briandav22** [comment]
Ok this feature should be working. 

You will need to update the plugin. In order to do this on the grafana server, navigate into the scrutinizer-datasource

Linux : ‘/var/lib/grafana/plugins/scrutinizer-datasource’
Windows : ‘/data/plugins/scrutinizer-datasource’ 

from there, pull down the latest version with 'git pull'. 

Let me know if you run into any issues at all.
